# Generated by Django 2.2.4 on 2019-11-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20191119_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
